### Register a User
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "ramu",
    "email": "ramu@example.com",
    "password": "ramu123",
    "role": "admin"
}

### Login a User
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "ramu@example.com",
    "password": "ramu123"
}

### User Can Create blog who has role admin
POST http://localhost:3000/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ
Content-Type: application/json

{
  "title":"Blog Post 5",
  "content": "Content for blog post 5",
  "editor_id":3
}

### user can update the blog who has role admin or editor for the perticular blog
PUT http://localhost:3000/blogs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ
Content-Type: application/json

{
  "title":"Get Job",
  "content": "Here is the opportunity to get jobs",
  "editor_id":3
}

### user can delete blog if he is admin
DELETE http://localhost:3000/blogs/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ

### Users can only view blogs
GET http://localhost:3000/blogs-view
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ

### Users can only view comments for blogs
GET http://localhost:3000/comments/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ

### Users can comment for the blogs
POST http://localhost:3000/comment-blog/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ
Content-Type: application/json

{
  "content": "I love Appening"
}

### User can delete their own comment
DELETE http://localhost:3000/comments/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbXVAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3Mzc2NTY2MTJ9.uMkZNleABIEAxMXk-4fA586OKk9pLT5qP7VA4ar71RQ

